baseUrl = "https://example.com/"
languageCode = "en-us"
title = "One slime to rule them all"
theme = "hello-friend"
copyright = ""
paginate = 5

[params]
  subtitle = "I like slime!"

[params.logo]
logoText = "hello friennnnnd"
#   or
#
# path = "/img/nova.jpg"
#   alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"